name: Docker Image CI

on:
  push:
    branches-ignore:
    - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and (not) push
        uses: docker/build-push-action@v5
        repository: ${{github.repository}}
        tag_with_ref: true
        tag_with_she: true
        tags: ${{github.sha}}
